In [1]:
from selenium import webdriver
from selenium.webdriver.firefox.service import Service
from webdriver_manager.firefox import GeckoDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd

In [2]:
options = webdriver.FirefoxOptions()
options.add_argument("--headless")  # Run in headless mode (no GUI)
driver = webdriver.Firefox(service=Service(GeckoDriverManager().install()), options=options)

In [3]:
dfs_list = []
month_names = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
for i in range(9):
    for month in range(12):
        year = 2016+i
        url2 = "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028802&pickMembers%5B0%5D=1.1&pickMembers%5B1%5D=3.1&cubeTimeFrame.startMonth=" + "{:02d}".format(month+1) + "&cubeTimeFrame.startYear=" + str(year) + "&referencePeriods=" + str(year) + "{:02d}".format(month+1) + "01%2C" + str(year) + "{:02d}".format(month+1) + "01"        
        driver.get(url2)
        wait = WebDriverWait(driver, 10)
        table = wait.until(EC.presence_of_element_located((By.TAG_NAME, "table")))
        table_html = table.get_attribute('outerHTML')
        df_temp = pd.read_html(table_html)[0]
        df_temp = df_temp.iloc[[0,1,2,3,4,5],[0,3]]
        new_header = df_temp.iloc[0]
        df_temp = df_temp[1:]
        df_temp.columns = ['Class of Employee', month_names[month] + " " + str(year)]
        dfs_list.append(df_temp)

In [4]:
dfs_list

[                        Class of Employee January 2016
 1  Total employed, all classes of workers      17871.6
 2                               Employees      15204.3
 3                Public sector employees8       3516.5
 4               Private sector employees9      11687.8
 5                         Self-employed10       2667.3,
                         Class of Employee February 2016
 1  Total employed, all classes of workers       17889.0
 2                               Employees       15213.1
 3                Public sector employees8        3513.0
 4               Private sector employees9       11700.1
 5                         Self-employed10        2675.9,
                         Class of Employee March 2016
 1  Total employed, all classes of workers    17892.8
 2                               Employees    15220.2
 3                Public sector employees8     3499.1
 4               Private sector employees9    11721.2
 5                         Self-employed10     2672.6,
                         Class of Employee April 2016
 1  Total employed, all classes of workers    17919.7
 2                               Employees    15256.9
 3                Public sector employees8     3504.4
 4               Private sector employees9    11752.6
 5                         Self-employed10     2662.8,
                         Class of Employee May 2016
 1  Total employed, all classes of workers  17947.4
 2                               Employees  15273.4
 3                Public sector employees8   3525.7
 4               Private sector employees9  11747.7
 5                         Self-employed10   2674.0,
                         Class of Employee June 2016
 1  Total employed, all classes of workers   17954.5
 2                               Employees   15258.7
 3                Public sector employees8    3497.2
 4               Private sector employees9   11761.5
 5                         Self-employed10    2695.8,
                         Class of Employee July 2016
 1  Total employed, all classes of workers   17943.2
 2                               Employees   15256.9
 3                Public sector employees8    3489.0
 4               Private sector employees9   11767.9
 5                         Self-employed10    2686.3,
                         Class of Employee August 2016
 1  Total employed, all classes of workers     17994.2
 2                               Employees     15332.9
 3                Public sector employees8      3515.1
 4               Private sector employees9     11817.8
 5                         Self-employed10      2661.3,
                         Class of Employee September 2016
 1  Total employed, all classes of workers        18032.5
 2                               Employees        15349.5
 3                Public sector employees8         3506.4
 4               Private sector employees9        11843.1
 5                         Self-employed10         2683.0,
                         Class of Employee October 2016
 1  Total employed, all classes of workers      18051.2
 2                               Employees      15377.5
 3                Public sector employees8       3526.6
 4               Private sector employees9      11850.9
 5                         Self-employed10       2673.8,
                         Class of Employee November 2016
 1  Total employed, all classes of workers       18076.0
 2                               Employees       15420.5
 3                Public sector employees8        3544.3
 4               Private sector employees9       11876.3
 5                         Self-employed10        2655.5,
                         Class of Employee December 2016
 1  Total employed, all classes of workers       18104.0
 2                               Employees       15453.0
 3                Public sector employees8        3540.9
 4               Private sector employees9       11912.1
 5                         Self-employed10        2651.0,
                         Class of Employee January 2017
 1  Total employed, all classes of workers      18172.5
 2                               Employees      15501.3
 3                Public sector employees8       3540.2
 4               Private sector employees9      11961.1
 5                         Self-employed10       2671.2,
                         Class of Employee February 2017
 1  Total employed, all classes of workers       18216.6
 2                               Employees       15533.6
 3                Public sector employees8        3528.4
 4               Private sector employees9       12005.2
 5                         Self-employed10        2683.0,
                         Class of Employee March 2017
 1  Total employed, all classes of workers    18241.5
 2                               Employees    15563.0
 3                Public sector employees8     3529.3
 4               Private sector employees9    12033.7
 5                         Self-employed10     2678.4,
                         Class of Employee April 2017
 1  Total employed, all classes of workers    18271.6
 2                               Employees    15579.9
 3                Public sector employees8     3568.5
 4               Private sector employees9    12011.4
 5                         Self-employed10     2691.7,
                         Class of Employee May 2017
 1  Total employed, all classes of workers  18312.9
 2                               Employees  15612.1
 3                Public sector employees8   3582.1
 4               Private sector employees9  12030.0
 5                         Self-employed10   2700.8,
                         Class of Employee June 2017
 1  Total employed, all classes of workers   18371.4
 2                               Employees   15653.6
 3                Public sector employees8    3597.6
 4               Private sector employees9   12056.0
 5                         Self-employed10    2717.8,
                         Class of Employee July 2017
 1  Total employed, all classes of workers   18416.9
 2                               Employees   15679.9
 3                Public sector employees8    3603.0
 4               Private sector employees9   12076.9
 5                         Self-employed10    2737.1,
                         Class of Employee August 2017
 1  Total employed, all classes of workers     18436.4
 2                               Employees     15665.8
 3                Public sector employees8      3586.1
 4               Private sector employees9     12079.7
 5                         Self-employed10      2770.6,
                         Class of Employee September 2017
 1  Total employed, all classes of workers        18442.5
 2                               Employees        15681.5
 3                Public sector employees8         3615.1
 4               Private sector employees9        12066.4
 5                         Self-employed10         2761.0,
                         Class of Employee October 2017
 1  Total employed, all classes of workers      18475.1
 2                               Employees      15701.5
 3                Public sector employees8       3597.5
 4               Private sector employees9      12103.9
 5                         Self-employed10       2773.6,
                         Class of Employee November 2017
 1  Total employed, all classes of workers       18550.5
 2                               Employees       15757.2
 3                Public sector employees8        3607.6
 4               Private sector employees9       12149.6
 5                         Self-employed10        2793.3,
                         Class of Employee December 2017
 1  Total employed, all classes of workers       18619.7
 2                               Employees       15825.1
 3                Public sector employees8        3618.1
 4               Private sector employees9       12207.0
 5                         Self-employed10        2794.6,
                         Class of Employee January 2018
 1  Total employed, all classes of workers      18576.8
 2                               Employees      15771.5
 3                Public sector employees8       3613.7
 4               Private sector employees9      12157.7
 5                         Self-employed10       2805.3,
                         Class of Employee February 2018
 1  Total employed, all classes of workers       18570.3
 2                               Employees       15776.7
 3                Public sector employees8        3628.8
 4               Private sector employees9       12147.9
 5                         Self-employed10        2793.6,
                         Class of Employee March 2018
 1  Total employed, all classes of workers    18630.1
 2                               Employees    15827.3
 3                Public sector employees8     3632.2
 4               Private sector employees9    12195.1
 5                         Self-employed10     2802.8,
                         Class of Employee April 2018
 1  Total employed, all classes of workers    18613.0
 2                               Employees    15791.5
 3                Public sector employees8     3609.9
 4               Private sector employees9    12181.6
 5                         Self-employed10     2821.5,
                         Class of Employee May 2018
 1  Total employed, all classes of workers  18621.7
 2                               Employees  15826.7
 3                Public sector employees8   3629.3
 4               Private sector employees9  12197.4
 5                         Self-employed10   2795.0,
                         Class of Employee June 2018
 1  Total employed, all classes of workers   18677.6
 2                               Employees   15872.2
 3                Public sector employees8    3644.9
 4               Private sector employees9   12227.3
 5                         Self-employed10    2805.4,
                         Class of Employee July 2018
 1  Total employed, all classes of workers   18763.9
 2                               Employees   15951.6
 3                Public sector employees8    3718.9
 4               Private sector employees9   12232.7
 5                         Self-employed10    2812.4,
                         Class of Employee August 2018
 1  Total employed, all classes of workers     18704.7
 2                               Employees     15909.5
 3                Public sector employees8      3690.7
 4               Private sector employees9     12218.8
 5                         Self-employed10      2795.2,
                         Class of Employee September 2018
 1  Total employed, all classes of workers        18797.5
 2                               Employees        15986.8
 3                Public sector employees8         3681.8
 4               Private sector employees9        12305.0
 5                         Self-employed10         2810.7,
                         Class of Employee October 2018
 1  Total employed, all classes of workers      18814.9
 2                               Employees      16006.7
 3                Public sector employees8       3663.9
 4               Private sector employees9      12342.9
 5                         Self-employed10       2808.2,
                         Class of Employee November 2018
 1  Total employed, all classes of workers       18869.4
 2                               Employees       16054.2
 3                Public sector employees8        3675.5
 4               Private sector employees9       12378.7
 5                         Self-employed10        2815.2,
                         Class of Employee December 2018
 1  Total employed, all classes of workers       18892.8
 2                               Employees       16044.9
 3                Public sector employees8        3680.7
 4               Private sector employees9       12364.2
 5                         Self-employed10        2847.9,
                         Class of Employee January 2019
 1  Total employed, all classes of workers      18920.5
 2                               Employees      16132.6
 3                Public sector employees8       3688.5
 4               Private sector employees9      12444.1
 5                         Self-employed10       2788.0,
                         Class of Employee February 2019
 1  Total employed, all classes of workers       18965.7
 2                               Employees       16173.7
 3                Public sector employees8        3695.2
 4               Private sector employees9       12478.5
 5                         Self-employed10        2792.0,
                         Class of Employee March 2019
 1  Total employed, all classes of workers    18932.9
 2                               Employees    16132.4
 3                Public sector employees8     3692.1
 4               Private sector employees9    12440.3
 5                         Self-employed10     2800.5,
                         Class of Employee April 2019
 1  Total employed, all classes of workers    19053.7
 2                               Employees    16247.8
 3                Public sector employees8     3725.8
 4               Private sector employees9    12522.0
 5                         Self-employed10     2806.0,
                         Class of Employee May 2019
 1  Total employed, all classes of workers  19067.3
 2                               Employees  16273.5
 3                Public sector employees8   3707.5
 4               Private sector employees9  12566.0
 5                         Self-employed10   2793.8,
                         Class of Employee June 2019
 1  Total employed, all classes of workers   19078.6
 2                               Employees   16269.6
 3                Public sector employees8    3710.7
 4               Private sector employees9   12558.9
 5                         Self-employed10    2809.0,
                         Class of Employee July 2019
 1  Total employed, all classes of workers   19072.4
 2                               Employees   16260.7
 3                Public sector employees8    3751.0
 4               Private sector employees9   12509.7
 5                         Self-employed10    2811.7,
                         Class of Employee August 2019
 1  Total employed, all classes of workers     19133.9
 2                               Employees     16308.7
 3                Public sector employees8      3767.5
 4               Private sector employees9     12541.2
 5                         Self-employed10      2825.2,
                         Class of Employee September 2019
 1  Total employed, all classes of workers        19142.8
 2                               Employees        16296.2
 3                Public sector employees8         3756.6
 4               Private sector employees9        12539.6
 5                         Self-employed10         2846.6,
                         Class of Employee October 2019
 1  Total employed, all classes of workers      19130.9
 2                               Employees      16301.3
 3                Public sector employees8       3765.9
 4               Private sector employees9      12535.5
 5                         Self-employed10       2829.6,
                         Class of Employee November 2019
 1  Total employed, all classes of workers       19096.8
 2                               Employees       16266.1
 3                Public sector employees8        3756.1
 4               Private sector employees9       12510.0
 5                         Self-employed10        2830.7,
                         Class of Employee December 2019
 1  Total employed, all classes of workers       19186.5
 2                               Employees       16358.0
 3                Public sector employees8        3747.5
 4               Private sector employees9       12610.5
 5                         Self-employed10        2828.5,
                         Class of Employee January 2020
 1  Total employed, all classes of workers      19204.7
 2                               Employees      16363.7
 3                Public sector employees8       3764.3
 4               Private sector employees9      12599.4
 5                         Self-employed10       2841.0,
                         Class of Employee February 2020
 1  Total employed, all classes of workers       19202.9
 2                               Employees       16410.1
 3                Public sector employees8        3771.5
 4               Private sector employees9       12638.6
 5                         Self-employed10        2792.8,
                         Class of Employee March 2020
 1  Total employed, all classes of workers    18058.2
 2                               Employees    15288.8
 3                Public sector employees8     3607.7
 4               Private sector employees9    11681.1
 5                         Self-employed10     2769.3,
                         Class of Employee April 2020
 1  Total employed, all classes of workers    16085.8
 2                               Employees    13357.1
 3                Public sector employees8     3548.7
 4               Private sector employees9     9808.4
 5                         Self-employed10     2728.7,
                         Class of Employee May 2020
 1  Total employed, all classes of workers  16410.7
 2                               Employees  13709.8
 3                Public sector employees8   3582.3
 4               Private sector employees9  10127.5
 5                         Self-employed10   2700.9,
                         Class of Employee June 2020
 1  Total employed, all classes of workers   17469.4
 2                               Employees   14749.2
 3                Public sector employees8    3643.2
 4               Private sector employees9   11106.0
 5                         Self-employed10    2720.2,
                         Class of Employee July 2020
 1  Total employed, all classes of workers   17895.5
 2                               Employees   15148.2
 3                Public sector employees8    3680.1
 4               Private sector employees9   11468.0
 5                         Self-employed10    2747.4,
                         Class of Employee August 2020
 1  Total employed, all classes of workers     18129.3
 2                               Employees     15405.2
 3                Public sector employees8      3718.1
 4               Private sector employees9     11687.1
 5                         Self-employed10      2724.1,
                         Class of Employee September 2020
 1  Total employed, all classes of workers        18555.9
 2                               Employees        15856.7
 3                Public sector employees8         3819.4
 4               Private sector employees9        12037.4
 5                         Self-employed10         2699.2,
                         Class of Employee October 2020
 1  Total employed, all classes of workers      18616.4
 2                               Employees      15905.5
 3                Public sector employees8       3864.0
 4               Private sector employees9      12041.5
 5                         Self-employed10       2710.9,
                         Class of Employee November 2020
 1  Total employed, all classes of workers       18650.0
 2                               Employees       15958.2
 3                Public sector employees8        3871.2
 4               Private sector employees9       12087.0
 5                         Self-employed10        2691.9,
                         Class of Employee December 2020
 1  Total employed, all classes of workers       18591.7
 2                               Employees       15920.5
 3                Public sector employees8        3896.9
 4               Private sector employees9       12023.6
 5                         Self-employed10        2671.2,
                         Class of Employee January 2021

In [6]:
dfs = [df.set_index('Class of Employee') for df in dfs_list]

In [7]:
df_new = pd.concat(dfs, axis=1)

In [8]:
df_new

,January 2016,February 2016,March 2016,April 2016,May 2016,June 2016,July 2016,August 2016,September 2016,October 2016,...,March 2024,April 2024,May 2024,June 2024,July 2024,August 2024,September 2024,October 2024,November 2024,December 2024
Class of Employee,,,,,,,,,,,,,,,,,,,,,
"Total employed, all classes of workers",17871.6,17889.0,17892.8,17919.7,17947.4,17954.5,17943.2,17994.2,18032.5,18051.2,...,20614.5,20700.5,20698.3,20715.9,20712.9,20742.6,20779.3,20782.6,20826.4,20917.4
Employees,15204.3,15213.1,15220.2,15256.9,15273.4,15258.7,15256.9,15332.9,15349.5,15377.5,...,17957.0,18024.7,18020.1,18042.4,18048.1,18084.8,18095.5,18081.6,18130.4,18207.9
Public sector employees8,3516.5,3513.0,3499.1,3504.4,3525.7,3497.2,3489.0,3515.1,3506.4,3526.6,...,4434.9,4445.1,4441.2,4441.9,4490.6,4489.4,4465.2,4443.4,4492.3,4530.3
Private sector employees9,11687.8,11700.1,11721.2,11752.6,11747.7,11761.5,11767.9,11817.8,11843.1,11850.9,...,13522.1,13579.6,13578.9,13600.5,13557.5,13595.5,13630.2,13638.2,13638.1,13677.5
Self-employed10,2667.3,2675.9,2672.6,2662.8,2674.0,2695.8,2686.3,2661.3,2683.0,2673.8,...,2657.5,2675.8,2678.2,2673.5,2664.8,2657.7,2683.8,2701.0,2696.0,2709.5

In [13]:
df_new.to_csv('canada_employees.csv')